### ISSUE TITLE
Go to definition 안되는 issue, 일부분 code 색이 안 칠해짐.

### ISSUE THREAD

**Issue by ghost** [pbkit/vscode-pbkit#14]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/89064304/155907420-f5eeea79-3831-4d1d-a2dd-653a5a4d183f.png">  
위 사진처럼 service 선언부와 import statement, 그리고 message의 앞부분 색이 안 칠해집니다.  

또한 Go to definition 기능이 동작하지 않는 것 같습니다. field에 우클릭을 해도 옵션이 뜨지 않네요

**Comment by disjukr** [comment]
아직 해당 기능이 들어간 버전이 릴리즈되지 않았습니다.
