### ISSUE TITLE
publish to openvsx

### ISSUE THREAD

**Issue by disjukr** [pbkit/vscode-pbkit#16]
https://github.com/eclipse/openvsx
to use in [VSCodium](https://vscodium.com/)

**Comment by SamB** [comment]
Hmm, looks like #19 is a more informative request for the same thing. It's kind of a mystery how the reporter of #19 missed this one, but I would suggest closing this as a duplicate of that one because it has a bit more guidance on how to get started.

**Comment by disjukr** [comment]
i agree :)
