### ISSUE TITLE
Support for Protocol Buffers Editions

### ISSUE THREAD

**Issue by luangong** [pbkit/vscode-pbkit#24]
References:

- [Protobuf Editions Overview](https://protobuf.dev/editions/overview/)
- [Feature Settings for Editions](https://protobuf.dev/editions/features/)
- [Changes Announced on June 29, 2023](https://protobuf.dev/news/2023-06-29/)
- ▶️ [Introducing Protobuf Editions](https://www.youtube.com/watch?v=8HbvEpeu1Lo)

**Comment by disjukr** [comment]
https://github.com/pbkit/vscode-pbkit/commit/eefacc0f7cc0731fc0f45cbb57f16deb0677bbe2
